### ISSUE TITLE
(request-target) should use path instead of URL

### ISSUE THREAD

**Issue by ewilde** [go-fed/httpsig#4]
## Description
Currently the `(request-target)` header is using URL; however it should according to the [spec](https://tools.ietf.org/html/draft-cavage-http-signatures-10#section-2.3) use the `path`

> If the header field name is `(request-target)` then generate the header field value by concatenating the lowercased :method, an ASCII space, and the :path pseudo-headers (as specified in HTTP/2, Section 8.1.2.3 [7]).  Note: For the avoidance of doubt, lowercasing only applies to the :method pseudo-header and not to the :path pseudo-header.

So currently:

`(request-target): post http://example.com/foo`

Should be:

`(request-target): post foo`

**Comment by cjslep** [comment]
Thanks for identifying this issue! 3b55e318d3fb044924403c3fa9028f833bab61db fixes this.

I still need to add a test to ensure this behavior is correct.
