### ISSUE TITLE
Signature verification : Digest should be calculated upfront using the body

### ISSUE THREAD

**Issue by Milkhaa** [go-fed/httpsig#6]
At the time of verification, we use the value of digest header(if required) for verifying signature.
This opens a gate to the attackers. Suppose someone was able to tamper with the request/response body without touching any of the headers, signature verification will still be OK because we are using the digest header sent for the verification purpose.

To prevent such attack , we should
Either,
i) recalculate the 'digest' to be used in signature verification.
Or,
ii)Compare the[ 'digest' header value] with the [re-calculated 'digest' from body] , if the signature calculation method for verification remains as is.

**Comment by cjslep** [comment]
Thanks for identifying and filing this issue.

I'll take a look at solving this soon.

**Comment by cjslep** [comment]
This feature request is pretty much implementing RFC 3230 in addition to the HTTP Signatures spec.

I've currently gotten the implementation done in this file:
https://github.com/go-fed/httpsig/blob/master/digest.go
and it is tested here:
https://github.com/go-fed/httpsig/blob/master/digest_test.go

...but it still needs to be hooked into the main API.

Note this will be a breaking change:
If already setting `"Digest"` headers manually, errors will now be thrown. Received `Digest` headers require reading the body, so it'll be likely the verifying API will also need to return a `bytes.Buffer` of the body in the request.

**Comment by cjslep** [comment]
And, as per usual, I don't support all the `"Digest"` hash schemes listed in the IANA list:
https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml

As I don't want to encourage adopters to use hashes with known weaknesses (MD5 or SHA1) or any of the other 4 that I don't really know whether they have known weaknesses.

**Comment by cjslep** [comment]
8d61ea6a9aa6290011d37b815fbca0beed6819ff now adds this feature.

**Comment by Milkhaa** [comment]
Thanks @cjslep  for adding the feature. Btw  in my code, I had added a wrapper over this library  in my code to support this Digest thing. We will refine these changes and put these out in the next release.
